# Generated by Django 6.1.1 on 2026-09-22 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticketType', models.CharField(choices=[('basic', 'Basic'), ('tour', 'Tour'), ('year', 'Yearly pass')], default='basic', max_length=10)),
                ('datePurchased', models.DateTimeField(auto_now_add=True)),
                ('dateStarting', models.DateTimeField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zoo_tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
