# Generated by Django 6.1.1 on 2026-09-29 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomSize', models.CharField(choices=[('small', 'Small'), ('average', 'Average'), ('large', 'Large')], default='average', max_length=10)),
                ('dateStarting', models.DateTimeField()),
                ('dateEnding', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zoo_hotelrooms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
